feat: add descriptions to the UI
hal-shu-sato/apm pull request #101
Opened 2021-09-07 10:48 UTC by mitosagi

## Description

Make the UI easier to understand.
- Detects aviutl that has been added manually.
- Displays information to help you decide which version to install.
- Clarifies how to add packages.

## Related Issue

## Motivation and Context

## How Has This Been Tested?

You can see it visually.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-09-07 12:36 UTC, hal-shu-sato requested changes
I felt some difficulty understanding.

2021-09-07 12:36 UTC, hal-shu-sato commented on src/index.html
> +								placeholder="追加プラグイン&スクリプト取得先（例: https://example.com/packages_list.xml）"
I think “追加プラグイン&スクリプト取得先” looks complicated.
But I don't have a good idea.

2021-09-07 12:36 UTC, hal-shu-sato commented on src/index.html
> +								追加プラグイン&スクリプト取得先を設定
Same as Line 366.

2021-09-07 22:41 UTC, mitosagi commented on src/index.html
> +								placeholder="追加プラグイン&スクリプト取得先（例: https://example.com/packages_list.xml）"
How about this?
データファイル取得先⇒データ取得先
追加データファイル取得先⇒追加パッケージ取得先

2021-09-08 04:27 UTC, hal-shu-sato commented on src/index.html
> +								placeholder="追加プラグイン&スクリプト取得先（例: https://example.com/packages_list.xml）"
Oh, looks better.
I think データ取得先 is good.

So, how about 追加データ取得先?
Maybe it's confusing...?

2021-09-08 11:26 UTC, mitosagi commented
I fixed it.

2021-09-08 11:28 UTC, hal-shu-sato approved these changes
Thank you for your improvement!!

2021-09-08 11:30 UTC, merged