feat: change to manage versions by JSON file in installation directory
hal-shu-sato/apm pull request #86
Opened 2021-09-03 15:26 UTC by hal-shu-sato

## Description

Now users can keep their data even if they change the installation path.

BREAKING CHANGE: All installation information will be reset.

## Related Issue

Closes #45 

## Motivation and Context

Reference #45 

## How Has This Been Tested?

OS: Windows 10 Home
Version: 21H1

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-09-03 15:27 UTC, hal-shu-sato commented
@mitosagi Could you please debug this?

2021-09-04 00:03 UTC, mitosagi requested changes
I don't see any problem with the code added this time. However, there is a problem with apmJson.

2021-09-04 01:10 UTC, mitosagi commented on src/plugin/plugin.js
>        this.setPluginsList(instPath);
Sorry. This bug seems to be unrelated to PR.

2021-09-04 01:12 UTC, mitosagi commented on src/script/script.js
>        this.setScriptsList(instPath);
Sorry. This bug seems to be unrelated to PR.

2021-09-04 04:26 UTC, hal-shu-sato commented
I fixed it.

2021-09-04 05:01 UTC, merged